import { notFound } from "next/navigation";
import { monthlyStayGuide } from "@/src/seo/monthly-stays";
import { requestLanguage } from "@/src/i18n/server";
import { copy,localizedHref } from "@/src/i18n/config";
import { informationalIndexingEnabled,localizedMetadata } from "@/src/seo/public";
import { publicDirectorySnapshot } from "@/src/data/public-directory";
import { defaultCheckIn } from "@/src/core/search";
import ShareSearchButton from "@/components/ShareSearchButton";
import StayReadiness from "@/components/StayReadiness";
export async function generateMetadata({params}:{params:Promise<{destination:string}>}){const guide=monthlyStayGuide((await params).destination);if(!guide)return{};const lang=await requestLanguage();return localizedMetadata("/monthly-stays/"+guide.slug,lang,guide.destination+copy(lang," monthly hotel stays · 30–90 nights"," · Hoteles para 30–90 noches"),copy(lang,"Plan a month or a season in ","Prepara un mes o una temporada en ")+guide.destination+copy(lang,". Compare areas, build a hotel shortlist and request a rate for your dates.",". Compara zonas, elige hoteles y solicita una tarifa para tus fechas."),informationalIndexingEnabled())}
export default async function MonthlyStays({params}:{params:Promise<{destination:string}>}){
 const guide=monthlyStayGuide((await params).destination);if(!guide)notFound();const lang=await requestLanguage();const t=(en:string,es:string)=>copy(lang,en,es),local=(path:string)=>localizedHref(path,lang);
 const hotels=publicDirectorySnapshot(6,{q:guide.destination,searchScope:"destination"}).hotels;
 const query=new URLSearchParams({q:guide.destination,searchScope:"destination",duration:"60",occupancy:"1",checkIn:defaultCheckIn()}).toString();
 return <main className="seoPage monthlyGuide"><div className="shell"><a href={local("/")} className="eyebrow">← ATLAS LONG STAY</a><section className="seoHero"><div className="eyebrow">30 / 60 / 90 {t("NIGHTS","NOCHES")}</div><h1>{t("A month or a season in ","Un mes o una temporada en ")}{guide.destination}.</h1><p>{t("Choose a place for everyday life, not just a weekend. Start with an area, a comfortable budget and the dates that work for you.","Elige un lugar para tu vida diaria, además de tus vacaciones. Empieza por una zona, un presupuesto cómodo y las fechas que te convengan.")}</p><div className="actions"><a className="btn" href={local("/stays")+"?"+query}>{t("Explore hotels →","Explorar hoteles →")}</a><ShareSearchButton query={query}/></div></section>
 <section className="editorialBody"><h2>{t("Choose the area before the room.","Elige la zona antes que la habitación.")}</h2><p>{t("The right long stay depends on what you do each day. Use the map to check exact locations and ask the hotel to confirm the details that matter to you.","La estancia adecuada depende de lo que hagas cada día. Utiliza el mapa para comprobar ubicaciones exactas y pide al hotel que confirme los detalles que te importan.")}</p><div className="seoGrid">{guide.zones.map(zone=><article className="card" key={zone.name}><h3>{zone.name}</h3><p>{lang==="es"?zone.es:zone.en}</p></article>)}</div><p><a href={guide.source} target="_blank" rel="noreferrer">{t("Official destination information ↗","Información turística oficial ↗")}</a> · {t("Atlas planning guidance reviewed 6 October 2026.","Orientación de Atlas revisada el 6 de octubre de 2026.")}</p></section>
 <section><div className="sectionTitle"><h2>{t("Start your hotel shortlist.","Empieza tu selección de hoteles.")}</h2><p>{t("These are real hotel listings. A listing is not a contracted partner or a guaranteed monthly rate.","Estas fichas identifican hoteles reales. Una ficha no implica un acuerdo con Atlas ni una tarifa mensual garantizada.")}</p></div><div className="hotels realHotelGrid">{hotels.map(h=><article className="card" key={h.id}><h3>{h.name}</h3><p>{h.address||h.city+", "+h.country}</p><a className="btn ghost" href={local("/stays/"+encodeURIComponent(h.id))+"?"+query}>{t("Request a rate for my dates →","Solicitar tarifa para mis fechas →")}</a></article>)}</div></section>
 <section className="editorialBody"><h2>{t("Make the budget comparable.","Compara presupuestos equivalentes.")}</h2><p>{t("Compare the total for the same dates, number of guests and room conditions. Atlas expresses a verified total as a 30-night equivalent; this is not a promise of a monthly contract.","Compara el total para las mismas fechas, huéspedes y condiciones de habitación. Atlas expresa un total verificado como equivalente por 30 noches; esto no garantiza un contrato mensual.")}</p><ul>{[t("Confirm meals, taxes and cancellation terms.","Confirma comidas, impuestos y condiciones de cancelación."),t("Ask about laundry, Wi-Fi, room cleaning and access to facilities.","Pregunta por lavandería, wifi, limpieza y acceso a servicios."),t("Check the full dates and whether the same room is available throughout.","Comprueba las fechas completas y si podrás mantener la misma habitación."),t("Keep transport and everyday spending separate from accommodation.","Separa transporte y gastos cotidianos del alojamiento.")].map(x=><li key={x}>{x}</li>)}</ul><h2>{t("How a private rate request works.","Cómo funciona una solicitud de tarifa.")}</h2><p>{t("Select a hotel, confirm your dates and budget, and leave an email for the quote. Follow progress from My requests. A request does not book a room or charge your card. Review the current price and the booking provider's terms before proceeding.","Selecciona un hotel, confirma fechas y presupuesto e indica un email para el presupuesto. Sigue el estado desde Mis solicitudes. Solicitar no reserva una habitación ni cobra tu tarjeta. Revisa el precio vigente y las condiciones del proveedor antes de continuar.")}</p></section>
 <StayReadiness duration={60}/><div className="actions"><a className="btn" href={local("/stays")+"?"+query}>{t("Find my next season →","Buscar mi próxima temporada →")}</a><a href={local("/monthly-stays/"+(guide.slug==="tenerife"?"gran-canaria":"tenerife"))}>{t("Compare another island →","Explorar otra isla →")}</a><a href={local("/for-hotels")}>{t("I represent a hotel →","Represento a un hotel →")}</a></div></div></main>;
}
