import { notFound } from "next/navigation";
import { comparisonIds,publicSearchQuery } from "@/src/core/shared-search";
import { resolveDirectoryHotel } from "@/src/services/directory";
import { requestLanguage } from "@/src/i18n/server";
import { copy,localizedHref } from "@/src/i18n/config";
import { defaultCheckIn } from "@/src/core/search";
import { listSellableOffers } from "@/src/db/catalog";
import ShareSearchButton from "@/components/ShareSearchButton";
import SaveHotelButton from "@/components/SaveHotelButton";
export async function generateMetadata(){const language=await requestLanguage();return{title:copy(language,"Compare hotels","Comparar hoteles"),robots:{index:false,follow:true}}}
export default async function Compare({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
  const p=await searchParams;const value=(key:string)=>Array.isArray(p[key])?p[key][0]:p[key];
  const ids=comparisonIds(value("ids")),language=await requestLanguage();
  const t=(en:string,es:string)=>copy(language,en,es),local=(path:string)=>localizedHref(path,language);
  const hotels=(await Promise.all(ids.map(resolveDirectoryHotel))).filter(h=>h!==null);if(ids.length&&!hotels.length)notFound();
  const query=publicSearchQuery(new URLSearchParams(Object.fromEntries(Object.keys(p).flatMap(key=>value(key)?[[key,value(key)!]]:[]))).toString());
  const checkIn=/^\d{4}-\d{2}-\d{2}$/.test(value("checkIn")||"")?value("checkIn")!:defaultCheckIn();const nights=[30,60,90,120,180,365].includes(Number(value("duration")))?Number(value("duration")):60;const occupancy=value("occupancy")==="2"?2:1;
  const offers=await Promise.all(hotels.map(async h=>(await listSellableOffers({q:h.name,checkIn,nights,occupancy,flexibleDays:0,limit:12})).find(o=>o.name.toLowerCase()===h.name.toLowerCase()&&o.city.toLowerCase()===h.city.toLowerCase()&&o.country.toLowerCase()===h.country.toLowerCase())));
  return <main className="seoPage"><div className="shell"><a className="backLink" href={local("/stays")+"?"+query}>{t("← Back to search","← Volver a la búsqueda")}</a><section className="seoHero"><h1>{t("Your next season, side by side.","Tu próxima temporada, frente a frente.")}</h1><p>{t("Compare up to three real hotels for the same dates and guests. Unconfirmed details stay clearly marked.","Compara hasta tres hoteles reales para las mismas fechas y huéspedes. Los datos sin confirmar se indican claramente.")}</p></section>
  {hotels.length?<><ShareSearchButton query={query} hotelIds={hotels.map(h=>h.id)}/><div className="comparisonGrid">{hotels.map((h,i)=>{const offer=offers[i];const detail=new URLSearchParams(query);detail.set("duration",String(nights));detail.set("occupancy",String(occupancy));detail.set("checkIn",checkIn);detail.set("returnTo",local("/compare")+"?"+query+"&ids="+ids.join(","));return <article className="card comparisonCard" key={h.id}><div className="comparisonMedia">{h.photoUrls?.[0]?<img src={h.photoUrls[0]} alt={h.name} loading="lazy" referrerPolicy="no-referrer"/>:<div className="travelFallback"><span>{h.city}</span><small>{h.country}</small></div>}</div><h2>{h.name}</h2><p>{h.address||h.city+", "+h.country}</p><dl><dt>{t("Stay","Estancia")}</dt><dd>{nights} {t("nights","noches")} · {occupancy} {t("guests","huéspedes")}</dd><dt>{t("Current price","Precio vigente")}</dt><dd>{offer?new Intl.NumberFormat(language,{style:"currency",currency:offer.currency}).format(offer.displayPrice)+t(" total"," total"):t("Request a rate for these dates","Solicita una tarifa para estas fechas")}</dd><dt>{t("Facilities","Servicios")}</dt><dd>{h.facilities?.length?h.facilities.join(" · "):t("Ask with your quote","Consulta con tu presupuesto")}</dd><dt>{t("Meals","Comidas")}</dt><dd>{offer?.board||t("Not confirmed","Sin confirmar")}</dd><dt>{t("Cancellation","Cancelación")}</dt><dd>{offer?.cancellation||t("Not confirmed","Sin confirmar")}</dd></dl><a className="btn" href={local("/stays/"+encodeURIComponent(h.id))+"?"+detail}>{t("Review hotel →","Consultar hotel →")}</a><SaveHotelButton hotel={{id:h.id,name:h.name,city:h.city,country:h.country,source:h.source}}/></article>})}</div></>:<div className="card"><p>{t("Choose hotels from search or your saved list to compare them here.","Selecciona hoteles del buscador o de tus favoritos para compararlos aquí.")}</p><a className="btn" href={local("/saved")}>{t("My saved hotels →","Mis hoteles guardados →")}</a></div>}</div></main>;
}
