"use client";
import { useState } from "react";
import { useLanguage } from "@/components/LanguageProvider";
import { copy,type Language } from "@/src/i18n/config";
import { campaignChannels } from "@/src/growth/campaigns";
export default function CampaignKit({base}:{base:string}){
 const currentLanguage=useLanguage(),[lang,setLang]=useState<Language>(currentLanguage),t=(en:string,es:string)=>copy(lang,en,es);const[destination,setDestination]=useState("tenerife"),[channel,setChannel]=useState("community"),[campaign,setCampaign]=useState("canaries-winter-2026"),[creative,setCreative]=useState("season-60"),[message,setMessage]=useState("");
 const place=destination==="tenerife"?"Tenerife":"Gran Canaria",url=new URL((lang==="es"?"/es":"")+"/monthly-stays/"+destination,base);url.searchParams.set("utm_source",channel);url.searchParams.set("utm_medium",channel==="google"?"cpc":channel==="partner"?"referral":"social");url.searchParams.set("utm_campaign",campaign.replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,100));url.searchParams.set("utm_content",creative.replace(/[^a-zA-Z0-9_-]/g,"-").slice(0,100));
 const text=t("A month or a season in ","Un mes o una temporada en ")+place+t(". Explore real hotels for 30, 60 or 90 nights and request a rate for your dates.",". Explora hoteles reales para 30, 60 o 90 noches y solicita una tarifa para tus fechas.")+"\n"+url;
 const video=t("20-second walkthrough: 0–4s choose the destination; 4–9s open the map and compare hotels; 9–14s set dates and guests; 14–20s show the rate request and My requests. Do not display unverified prices or claim a confirmed booking.","Recorrido de 20 segundos: 0–4s elige destino; 4–9s abre el mapa y compara hoteles; 9–14s configura fechas y huéspedes; 14–20s muestra la solicitud de tarifa y Mis solicitudes. No muestres precios sin verificar ni presentes una reserva como confirmada.");
 async function clipboard(value:string){try{await navigator.clipboard.writeText(value);setMessage(t("Copied","Copiado"))}catch{setMessage(t("Select the text to copy it.","Selecciona el texto para copiarlo."))}}
 const ads={headlines:[t("A season in ","Una temporada en ")+place,t("Hotels for 30–90 nights","Hoteles para 30–90 noches"),t("Request your stay rate","Solicita tu tarifa")],descriptions:[t("Explore real hotels. Request a rate for your dates and review the terms.","Explora hoteles reales. Solicita una tarifa para tus fechas y revisa las condiciones.")]};
 function downloadCard(){const escape=(text:string)=>text.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&apos;"}[c]||c));const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350" viewBox="0 0 1080 1350"><rect width="1080" height="1350" fill="#071630"/><circle cx="900" cy="250" r="360" fill="#16345e"/><text x="80" y="125" fill="#d9ff72" font-family="Arial,sans-serif" font-size="38" font-weight="bold">ATLAS · LONG STAY</text><text x="80" y="455" fill="white" font-family="Arial,sans-serif" font-size="78" font-weight="bold">${escape(place)}</text><text x="80" y="585" fill="white" font-family="Arial,sans-serif" font-size="56">${escape(t("A whole season.","Toda una temporada."))}</text><text x="80" y="700" fill="#c8d2e5" font-family="Arial,sans-serif" font-size="40">${escape(t("30, 60 or 90 nights","30, 60 o 90 noches"))}</text><rect x="80" y="860" width="920" height="180" rx="25" fill="#d9ff72"/><text x="120" y="940" fill="#071630" font-family="Arial,sans-serif" font-size="40" font-weight="bold">${escape(t("Explore hotels.","Explora hoteles."))}</text><text x="120" y="995" fill="#071630" font-family="Arial,sans-serif" font-size="33">${escape(t("Request a rate for your dates.","Solicita tarifa para tus fechas."))}</text><text x="80" y="1170" fill="#c8d2e5" font-family="Arial,sans-serif" font-size="27">${escape(new URL(base).host)}</text><text x="80" y="1230" fill="#c8d2e5" font-family="Arial,sans-serif" font-size="24">${escape(t("Subject to confirmed rates and availability.","Sujeto a tarifa y disponibilidad confirmadas."))}</text></svg>`;const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml"}));link.download="atlas-"+destination+"-"+lang+".svg";link.click();URL.revokeObjectURL(link.href)}
 function download(){const blob=new Blob([JSON.stringify({url:url.toString(),social:text,searchAds:ads,videoStoryboard:video,searchKeywords:["monthly hotel "+place,"long stay hotel "+place,"hotel larga estancia "+place],negativeKeywords:["jobs","empleo","gratis","one night","una noche"],goal:"qualified_enquiry",budget:null,launchReady:false},null,2)],{type:"application/json"});const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download="atlas-campaign-"+destination+".json";link.click();URL.revokeObjectURL(link.href)}
 return <div className="campaignKit card"><div className="partnerFormGrid"><label>{t("Material language","Idioma del material")}<select value={lang} onChange={e=>setLang(e.target.value as Language)}><option value="es">Español</option><option value="en">English</option></select></label><label>{t("Destination","Destino")}<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="tenerife">Tenerife</option><option value="gran-canaria">Gran Canaria</option></select></label><label>{t("Channel","Canal")}<select value={channel} onChange={e=>setChannel(e.target.value)}>{campaignChannels.map(x=><option key={x}>{x}</option>)}</select></label><label>{t("Campaign","Campaña")}<input value={campaign} maxLength={100} onChange={e=>setCampaign(e.target.value)}/></label><label>{t("Creative","Creatividad")}<input value={creative} maxLength={100} onChange={e=>setCreative(e.target.value)}/></label></div><label>{t("Attributed link","Enlace con atribución")}<textarea readOnly value={url.toString()}/></label><label>{t("Social copy","Texto para redes")}<textarea readOnly value={text}/></label><p>{video}</p><label>{t("Search ad drafts","Borradores de anuncios de búsqueda")}<textarea readOnly value={[...ads.headlines,...ads.descriptions].join("\n")}/></label><div className="actions"><button className="btn" onClick={()=>clipboard(text)}>{t("Copy social post","Copiar publicación")}</button><button className="btn ghost" onClick={download}>{t("Download campaign pack","Descargar campaña")}</button><button className="btn ghost" onClick={downloadCard}>{t("Download social card","Descargar imagen para redes")}</button><a className="btn ghost" href={url.toString()}>{t("Review landing page →","Revisar página de destino →")}</a></div><p role="status">{message}</p><small>{t("This prepares materials. It does not send messages, launch ads or spend a budget.","Esta herramienta prepara materiales. No envía mensajes, lanza anuncios ni gasta presupuesto.")}</small></div>;
}
