"use client";
import { useEffect,useState } from "react";
import { useLanguage } from "@/components/LanguageProvider";
import { copy,localizedHref } from "@/src/i18n/config";
import type { CustomerRequest } from "@/src/db/customer-requests";
import { growthEvent } from "@/src/growth/client";
export default function CustomerRequests(){
  const lang=useLanguage();const[rows,setRows]=useState<CustomerRequest[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState(false);const[busy,setBusy]=useState<string|null>(null);
  async function refresh(){setLoading(true);setError(false);try{const r=await fetch("/api/requests",{cache:"no-store"});if(!r.ok)throw new Error();const data=await r.json();setRows(data.requests)}catch{setError(true)}finally{setLoading(false)}}
  useEffect(()=>{let alive=true;async function open(){const token=new URLSearchParams(window.location.hash.slice(1)).get("access");if(token){window.history.replaceState(null,"",window.location.pathname+window.location.search);const r=await fetch("/api/requests/access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token})}).catch(()=>null);if(!r?.ok){if(alive){setError(true);setLoading(false)}return}}if(alive)await refresh()}void open();return()=>{alive=false}},[]);
  async function accept(id:string){setBusy(id);setError(false);try{const r=await fetch("/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const data=await r.json();if(!r.ok||!data.path)throw new Error();growthEvent("quote_accepted",{request_id:id});window.location.assign(data.path)}catch{setError(true);setBusy(null)}}
  return <section className="requestsList" aria-busy={loading}><div className="actions"><button className="btn ghost" onClick={refresh} disabled={loading}>{copy(lang,"Refresh status","Actualizar estado")}</button><a href={localizedHref("/saved",lang)}>{copy(lang,"My saved hotels →","Mis hoteles guardados →")}</a></div>
    {error&&<p role="alert">{copy(lang,"We could not load this request. Reopen your email link or try again.","No hemos podido abrir la solicitud. Vuelve a abrir el enlace de tu email o inténtalo de nuevo.")}</p>}
    {loading?<p role="status">{copy(lang,"Loading your requests…","Cargando tus solicitudes…")}</p>:!rows.length&&!error?<div className="card"><h2>{copy(lang,"Your next season starts here.","Tu próxima temporada empieza aquí.")}</h2><p>{copy(lang,"Your requests appear in this browser. Open the private email link to follow one on another device.","Tus solicitudes aparecen en este navegador. Abre el enlace privado del email para consultar una desde otro dispositivo.")}</p><a className="btn" href={localizedHref("/stays",lang)}>{copy(lang,"Find a stay →","Buscar estancia →")}</a></div>:null}
    {rows.map(r=><article className="card requestCard" key={r.id}><div className="eyebrow">{r.status==="CLOSED"?copy(lang,"CLOSED","CERRADA"):r.offer?copy(lang,"QUOTE READY","PRESUPUESTO DISPONIBLE"):r.quote_sent_at?copy(lang,"PRICE NEEDS RECHECKING","TARIFA PENDIENTE DE ACTUALIZACIÓN"):copy(lang,"CHECKING YOUR DATES","COMPROBANDO TUS FECHAS")}</div><h2>{r.hotel_name}</h2><p>{r.city}, {r.country} · {r.check_in} · {r.nights} {copy(lang,"nights","noches")} · {r.occupancy} {copy(lang,"guests","huéspedes")}</p>
      <ol className="requestSteps"><li className="complete">{copy(lang,"Request received","Solicitud recibida")}</li><li className={r.quote_sent_at?"complete":"current"}>{copy(lang,"Rate checked","Tarifa comprobada")}</li><li className={r.quote_accepted_at?"complete":r.offer?"current":""}>{copy(lang,"Review and continue","Revisar y continuar")}</li></ol>
      {r.offer?<><div className="requestPrice"><b>{new Intl.NumberFormat(lang,{style:"currency",currency:r.offer.currency}).format(r.offer.displayPrice)}</b> {copy(lang,"total for the stay","total de la estancia")}<small>{new Intl.NumberFormat(lang,{style:"currency",currency:r.offer.currency}).format(r.offer.monthlyEquivalent)} {copy(lang,"per 30 nights equivalent","equivalente por 30 noches")}</small></div><p>{r.offer.board||copy(lang,"Meals: check conditions","Comidas: consulta las condiciones")} · {r.offer.cancellation||copy(lang,"Cancellation: check conditions","Cancelación: consulta las condiciones")}</p><button className="btn" onClick={()=>accept(r.id)} disabled={busy===r.id}>{copy(lang,"Review booking option →","Consultar opción de reserva →")}</button></>:<p>{copy(lang,"We have received your dates. A price will appear when an option is verified. No reservation or payment has been made.","Hemos recibido tus fechas. El precio aparecerá cuando comprobemos una opción. No se ha creado ninguna reserva ni realizado un cobro.")}</p>}
      <small>{copy(lang,"Request","Solicitud")} {r.id.slice(0,8)} · {copy(lang,"Continuing to booking does not confirm a reservation.","Continuar hacia la reserva no confirma una estancia.")}</small>
    </article>)}
  </section>;
}
