import type { Metadata } from "next";
import { canonicalSiteUrl } from "@/src/system/site-url";

export const metadata:Metadata={title:"Geographic Arbitrage Field Guide",description:"A practical guide to living for 30–90 days where your monthly budget buys more—without confusing hotel prices, immigration days or tax residence.",alternates:{canonical:canonicalSiteUrl()+"/geographic-arbitrage"}};

export default function GeographicArbitrage(){return <main className="seoPage"><div className="shell">
  <section className="seoHero"><div className="eyebrow">ATLAS FIELD NOTES · GEOGRAPHIC ARBITRAGE</div><h1>Earn in one economy.<br/>Live a season in another.</h1><p>Geographic arbitrage is not “cheap travel”. It is the decision to move a recurring monthly budget into a place where accommodation, climate and everyday life fit better for a defined period—without pretending legal constraints disappear.</p><div className="actions"><a className="btn" href="/stays?q=Tenerife&duration=60">Search a 60-day stay →</a><a className="btn ghost" href="/stay-readiness">Run the day-count checks</a></div></section>
  <div className="seoGrid">
    <article className="card"><div className="eyebrow">01 · MONEY</div><h2>Compare months, not nightly headlines.</h2><p>A 60-day decision should be compared on total stay cost and monthly equivalent. Atlas preserves the provider total and treats the monthly figure as a comparison unit—not a newly invented quote.</p></article>
    <article className="card"><div className="eyebrow">02 · SUPPLY</div><h2>Discovery is not inventory.</h2><p>A hotel can exist in the searchable universe without having a verified 30–90 day commercial rate. That gap is where private sourcing and negotiated hotel supply matter.</p></article>
    <article className="card"><div className="eyebrow">03 · MOBILITY</div><h2>Nights and immigration days differ.</h2><p>Hotel stays are sold in nights. Immigration rules frequently count calendar presence. A 90-night hotel stay can span 91 counted days, so route design must use the legal clock as well as the booking clock.</p></article>
    <article className="card"><div className="eyebrow">04 · TAX</div><h2>183 is a screen, not a magic shield.</h2><p>Day counts matter, but tax residence can also depend on domestic law, treaties, permanent home, family and economic interests. Atlas flags risk; it does not sell fake tax certainty.</p></article>
    <article className="card"><div className="eyebrow">05 · SEASONALITY</div><h2>The hotel has a reason to participate.</h2><p>The managed-marketplace thesis is strongest where hotels have predictable low-season capacity and travellers want long, stable occupancy. The first Atlas wedge is winter-sun demand, not every destination at once.</p></article>
    <article className="card"><div className="eyebrow">06 · DISTRIBUTION</div><h2>The best rate should close the loop.</h2><p>Affiliate redirects can bootstrap coverage. The defensible path is direct allocated supply that can be bought through Atlas when contract, inventory and payment gates are genuinely active.</p></article>
  </div>
  <section className="editorialBody"><h2>The Atlas thesis</h2><p>The long-term product is not a calculator and not an AI wrapper. It is a data and distribution system around 30–90 day demand: verified rates, allocated supply, sourcing response history, stay-readiness rules and transaction economics.</p><h2>Start narrow</h2><p>Prove one destination loop, measure actual conversion and unit economics, then copy the operating playbook. Expansion without supply proof is catalogue growth, not marketplace growth.</p></section>
</div></main>}
