import type { AdjacencyKind } from "@/src/adjacency/registry";
export type PublicPartnerReference={kind:AdjacencyKind;providerName:string;headline:string;description:string;serviceUrl:string;partnerProgramUrl:string;partnerProgramLabel:string;facts:string[]};
export const publicPartnerReferences:PublicPartnerReference[]=[
{kind:"flight",providerName:"Skyscanner",headline:"Search flights separately from the stay.",description:"Atlas never hides transport inside the hotel price. Skyscanner is an external metasearch reference; monetized tracking requires Atlas acceptance into its affiliate programme.",serviceUrl:"https://www.skyscanner.net/",partnerProgramUrl:"https://www.partners.skyscanner.net/product/affiliates",partnerProgramLabel:"Skyscanner affiliate programme",facts:["External flight marketplace","Affiliate tracking stays outside hotel economics","Atlas does not book tickets"]},
{kind:"insurance",providerName:"SafetyWing",headline:"Long-stay insurance stays optional.",description:"SafetyWing is an external insurance reference for people living internationally. Coverage, eligibility and claims remain controlled by the insurer and the policy terms.",serviceUrl:"https://safetywing.com/",partnerProgramUrl:"https://safetywing.com/ambassador",partnerProgramLabel:"SafetyWing Ambassador programme",facts:["External insurance provider","Referral programme available","Never bundled into hotel price"]},
{kind:"telemedicine",providerName:"Air Doctor",headline:"Healthcare access without pretending Atlas is a clinic.",description:"Air Doctor is an external traveler-health reference with clinic, hotel/home and video consultation options. Medical availability and suitability remain the provider's responsibility.",serviceUrl:"https://air-dr.com/",partnerProgramUrl:"https://air-dr.com/affiliate/",partnerProgramLabel:"Air Doctor affiliate programme",facts:["External medical network","Video consultation available through provider","Atlas does not provide medical care"]},
{kind:"transfer",providerName:"Welcome Pickups",headline:"Airport transfer as its own transaction.",description:"Welcome Pickups is an external ground-transfer reference with affiliate and partner integration options. The ride is never silently added to accommodation.",serviceUrl:"https://www.welcomepickups.com/",partnerProgramUrl:"https://partner.welcomepickups.com/affiliates/",partnerProgramLabel:"Welcome Pickups affiliates",facts:["External transfer provider","Affiliate links and widgets available","Separate price and terms"]},
{kind:"home-management",providerName:"Partner lane",headline:"Keep the home working while living elsewhere.",description:"The home-management lane is wired but intentionally has no default commercial provider. Atlas activates a tracked destination only after a real agreement and approved URL exist.",serviceUrl:"https://www.google.com/search?q=home+management+services",partnerProgramUrl:"https://www.google.com/search?q=home+management+affiliate+program",partnerProgramLabel:"Partner selection pending",facts:["No default provider is falsely claimed","Environment-driven referral lane already exists","Commercial activation requires a real agreement"]}
];
export const publicPartnerReference=(kind:string)=>publicPartnerReferences.find(x=>x.kind===kind)||null;
