import { listSellableOffers } from "@/src/db/catalog";
import { seoAutopilotEnabled } from "@/src/seo/live";
import { canonicalSiteUrl,customPublicDomainConfigured,searchConsoleVerificationConfigured } from "@/src/system/site-url";
import { seoGate } from "@/src/seo/gate";

export type EditorialPage={slug:string;title:string;description:string;query?:string;maxMonthly?:number;nights?:number;angle:string;questions:string[]};

export const EDITORIAL_PAGES:EditorialPage[]=[
{slug:"living-in-madrid-hotels-90-days",title:"Living in Madrid Hotels for 90 Days: Real Cost",description:"A data-led look at verified 90-day hotel costs in Madrid, what the monthly equivalent means and what changes the total.",query:"Madrid",nights:90,angle:"90-day city living",questions:["What does 90 days cost?","Which hotel terms matter most?","When is a monthly hotel better than a short rental?"]},
{slug:"hotel-vs-apartment-madrid-three-months",title:"Hotel vs Apartment in Madrid for a 3-Month Stay",description:"Compare the practical cost model of a hotel and an apartment for a three-month Madrid stay, using verified hotel evidence when available.",query:"Madrid",nights:90,angle:"hotel versus apartment",questions:["What is included in a hotel rate?","Which apartment costs are easy to miss?","Who benefits from flexibility?"]},
{slug:"where-1500-month-long-hotel-stay",title:"Where Can €1,500/Month Buy a Long Hotel Stay?",description:"A live evidence-led view of destinations where verified long-stay hotel rates fit within €1,500 per month.",maxMonthly:1500,angle:"budget discovery",questions:["Which countries appear?","How many verified options exist?","What does the monthly equivalent include?"]},
{slug:"best-winter-sun-90-day-stays",title:"Best Winter-Sun Destinations for a 90-Day Stay",description:"A practical 90-day winter-sun guide built around current long-stay hotel evidence rather than generic destination lists.",nights:90,angle:"winter sun",questions:["Where is a 90-day stay available?","What does it cost per month?","What should you verify before leaving?"]},
{slug:"live-in-hotels-year-2000-month",title:"Can You Live in Hotels for a Year for €2,000/Month?",description:"An evidence-first guide to the €2,000 monthly hotel-living question, including what current rates prove and what they do not.",maxMonthly:2000,angle:"year-round hotel living",questions:["How many markets fit?","What changes across seasons?","How should a reserve be planned?"]},
{slug:"tenerife-long-stay-hotel-price-index",title:"Tenerife Long-Stay Hotel Price Index",description:"Current verified long-stay hotel pricing for Tenerife, expressed as monthly equivalents with sample size and freshness.",query:"Tenerife",angle:"destination price index",questions:["What is the median monthly rate?","What is the current range?","How fresh is the sample?"]},
{slug:"europe-monthly-hotel-index",title:"Europe Monthly Hotel Index",description:"A data-led view of verified monthly-equivalent hotel rates across European long-stay markets.",angle:"regional price index",questions:["Which destinations are cheapest?","How wide is the price range?","How many offers are current?"]},
{slug:"madrid-monthly-hotels-guide",title:"Monthly Hotels in Madrid: A Long-Stay Guide",description:"How to evaluate Madrid hotels for month-long stays, including verified monthly prices, location and cancellation evidence.",query:"Madrid",angle:"monthly Madrid",questions:["What is available now?","Which rates are flexible?","How should you compare hotels?"]},
{slug:"tenerife-winter-long-stay-guide",title:"Tenerife Winter Long Stays: What a Month Really Costs",description:"A winter-focused Tenerife guide built around verified long-stay hotel rates and monthly-equivalent costs.",query:"Tenerife",angle:"winter Tenerife",questions:["What does a month cost?","Which stay lengths appear?","What evidence is current?"]},
{slug:"all-inclusive-long-stay-hotels",title:"All-Inclusive Long-Stay Hotels: Monthly Cost Guide",description:"How all-inclusive hotel stays translate into a monthly living budget when current verified offers exist.",angle:"all inclusive",questions:["What does all-inclusive cover?","How does monthly cost compare?","Where are current offers?"]},
{slug:"long-stay-hotel-cancellation-guide",title:"Long-Stay Hotel Cancellation: What to Check Before 90 Days",description:"A practical guide to cancellation evidence for 30–365 day hotel stays, with current examples when verified offers exist.",angle:"cancellation",questions:["What is refundable?","Why do long stays differ?","What should be checked before referral?"]},
{slug:"monthly-hotel-rate-explained",title:"What Is a Monthly Hotel Rate? Atlas Methodology",description:"How Atlas converts real stay prices into a comparable 30-day monthly equivalent without inventing or extrapolating availability.",angle:"methodology",questions:["How is monthly equivalent calculated?","What is not included?","When does a price expire?"]},
{slug:"long-stay-hotels-for-couples",title:"Long-Stay Hotels for Couples: How Monthly Cost Changes",description:"A current-evidence guide to occupancy, monthly-equivalent pricing and hotel selection for two-person long stays.",angle:"couples",questions:["How does occupancy change price?","Which board basis matters?","What makes a stay practical?"]},
{slug:"90-day-hotel-stay-guide",title:"How to Book a Hotel for 90 Days",description:"A step-by-step guide to evaluating, verifying and comparing a 90-day hotel stay without treating a nightly price as the whole story.",nights:90,angle:"90-day planning",questions:["How should dates be searched?","What needs verification?","How do you compare monthly cost?"]},
{slug:"30-vs-90-day-hotel-cost",title:"30 vs 90 Day Hotel Stays: How the Cost Changes",description:"A data-led framework for comparing 30-day and 90-day hotel stays using monthly-equivalent prices and current rate evidence.",angle:"duration comparison",questions:["Does longer always mean cheaper?","What fees change?","How should flexibility be valued?"]},
{slug:"hotel-living-budget-1800",title:"What Does an €1,800 Hotel-Living Budget Buy?",description:"Explore current long-stay hotel evidence around an €1,800 monthly budget and the trade-offs between location, board and flexibility.",maxMonthly:1800,angle:"budget 1800",questions:["How many options fit?","Which countries appear?","What terms differ?"]},
{slug:"hotel-living-budget-2500",title:"What Does a €2,500 Hotel-Living Budget Buy?",description:"A live-data framework for long-stay hotel choices around €2,500 per month.",maxMonthly:2500,angle:"budget 2500",questions:["Which markets open up?","What is the current median?","How many stays are verified?"]},
{slug:"seasonal-hotel-living-europe",title:"Seasonal Hotel Living in Europe: A Practical Guide",description:"How to build a seasonal European long-stay plan around hotel rates, stay length and changing availability.",angle:"seasonal Europe",questions:["How should seasons be sequenced?","What changes monthly cost?","How much flexibility is useful?"]},
{slug:"long-stay-hotels-healthcare-access",title:"Long-Stay Hotels and Healthcare Access",description:"A methodology-first guide to evaluating healthcare access alongside verified hotel evidence for longer stays.",angle:"healthcare",questions:["What can hotel data prove?","What needs external verification?","How should access affect a shortlist?"]},
{slug:"beach-hotels-monthly-stays",title:"Beach Hotels for Monthly Stays",description:"Current long-stay hotel evidence for travellers who want sea access without giving up monthly budget discipline.",angle:"beach",questions:["Where are current options?","What does a month cost?","Which facilities are actually verified?"]},
{slug:"long-stay-hotels-with-breakfast",title:"Long-Stay Hotels With Breakfast: Monthly Cost Guide",description:"How breakfast-inclusive hotel offers affect a monthly long-stay budget when board evidence is current.",angle:"breakfast",questions:["What is included?","How does board affect cost?","Which offers are current?"]},
{slug:"hotel-living-without-car",title:"Hotel Living Without a Car: What to Evaluate",description:"A practical framework for choosing a long-stay hotel when walkability and daily-life access matter more than a rental car.",angle:"car-free",questions:["What evidence can Atlas show?","What needs map validation?","How should location be weighted?"]},
{slug:"retirement-hotel-living-cost",title:"Retirement Hotel Living: How to Build a Real Monthly Budget",description:"A non-financial-advice framework for comparing long-stay hotel costs against a recurring monthly living budget.",angle:"retirement budget",questions:["What belongs in the budget?","How much reserve is sensible?","What costs sit outside the hotel?"]},
{slug:"remote-work-monthly-hotels",title:"Monthly Hotels for Remote Work: What to Check",description:"A long-stay hotel checklist for remote workers, separating verified property evidence from assumptions about connectivity and workspace.",angle:"remote work",questions:["What should be verified?","What can a hotel page prove?","How should cancellation be handled?"]},
{slug:"hotel-vs-serviced-apartment-long-stay",title:"Hotel vs Serviced Apartment for a Long Stay",description:"A decision framework for comparing hotels and serviced apartments over one to six months.",angle:"accommodation comparison",questions:["Which services are bundled?","How does flexibility differ?","How should total cost be compared?"]},
{slug:"long-stay-hotel-taxes-fees",title:"Long-Stay Hotel Taxes and Fees: What the Price May Miss",description:"A practical explanation of taxes, fees and inclusions around longer hotel stays and why Atlas tracks whether charges are included.",angle:"taxes and fees",questions:["Are taxes included?","What varies by destination?","What should be checked before booking?"]},
{slug:"long-stay-hotel-price-freshness",title:"Why Long-Stay Hotel Prices Expire",description:"How Atlas treats rate freshness, expiry and evidence so an old hotel price is not presented as bookable today.",angle:"price freshness",questions:["Why do prices expire?","What does verified mean?","When does Atlas remove a rate?"]},
{slug:"monthly-hotel-cost-methodology",title:"How Atlas Calculates Monthly Hotel Cost",description:"The exact monthly-equivalent methodology Atlas uses to compare stays of different lengths without changing the provider's total price.",angle:"calculation methodology",questions:["What is the formula?","What is preserved?","What is never inferred?"]},
{slug:"long-stay-hotel-data-sources",title:"Where Atlas Long-Stay Hotel Data Comes From",description:"A transparent guide to property identity, commercial rate evidence, content rights and the provenance Atlas keeps behind public hotel information.",angle:"data sources",questions:["What identifies a hotel?","Where do rates come from?","How are content rights handled?"]},
{slug:"how-atlas-verifies-hotel-rates",title:"How Atlas Verifies Long-Stay Hotel Rates",description:"A consumer-readable explanation of the checks Atlas applies before a hotel price can appear as current and available.",angle:"rate verification",questions:["What makes a rate current?","What makes it sellable?","What happens when evidence expires?"]},
];

export function editorialBySlug(slug:string){return EDITORIAL_PAGES.find(x=>x.slug===slug)||null}

export async function editorialEvidence(page:EditorialPage){
  let offers=await listSellableOffers({q:page.query,limit:100,...(page.nights?{nights:page.nights}:{}),...(page.maxMonthly?{maxMonthly:page.maxMonthly}:{})});
  if(page.maxMonthly)offers=offers.filter(o=>o.monthlyEquivalent<=page.maxMonthly!);
  if(page.nights)offers=offers.filter(o=>o.nights===page.nights);
  const fresh=offers.filter(o=>new Date(o.expiresAt||0).getTime()>Date.now());
  const canonical=canonicalSiteUrl()+"/guides/"+page.slug;
  const gate=seoGate({
    liveIndexingEnabled:seoAutopilotEnabled(),customDomain:customPublicDomainConfigured(),searchConsoleReady:searchConsoleVerificationConfigured(),
    uniqueCanonical:canonical.startsWith(canonicalSiteUrl()+"/"),uniqueCopy:page.description.length>=70,
    sellableHotels:new Set(fresh.map(o=>o.hotelId)).size,uniqueCountries:new Set(fresh.map(o=>o.country)).size,
    hasFreshProviderEvidence:fresh.length>0,nonEmptyIntent:Boolean(page.angle),structuredDataValid:fresh.every(o=>o.displayPrice>0&&Boolean(o.currency&&o.city&&o.country)),
  });
  return{offers:fresh,canonical,gate};
}
